name: Deploy Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'  # Nur triggern wenn sich was im frontend-Ordner ändert
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'

defaults:
  run:
    working-directory: frontend  # Setzt das Arbeitsverzeichnis für alle run-Befehle

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json  # Wichtig für npm cache
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check formatting
      run: npm run format:check
    
    - name: Run linter
      run: npm run lint
    
    - name: Build
      run: npm run build
      
    - name: Configure AWS credentials
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        
    - name: Deploy to S3
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: npm run sync
